### ISSUE TITLE
Needless repetition ..

### ISSUE THREAD

**Issue by skx** [x08d/lockdown.sh#1]
If you're expecting unattended-upgrades to provide (security) upgrades, automatically then this section of code is pointless:

```
# Add Daily Update Cron Job
touch job
echo "@daily apt update; apt dist-upgrade -y" >> job
crontab job
rm job
```

* Note: The more idiomatic approach would be writing to `/etc/cron.daily/apt-upgrade`, or similar.  Not using cron.

However I note that you never actually _install_ `unattended-upgrades`, only attempt to reconfigure it.  That's probably a mistake.

**Comment by MartinVerges** [comment]
please use systemd timers, a newer approach with some nice benefits

**Comment by ghost** [comment]
Cool, thanks for opening an issue!
